from tkinter import *
window=Tk()
window.title('Sample Window')
window.geometry('300x300')
greeting=Label(text="Hello User",fg="Black",bg="White")
button=Button(text="Click here",bg="Black",fg='white')
entry=Entry(fg="Black",bg="Yellow",width=50)
greeting.pack()
button.pack()
entry.pack()
frame=Frame(master=window, relief=RAISED, borderwidth=5)
frame.pack()
label=Label(master=frame,text="Sample frame")
label.pack()
textbox=Text(fg='green', bg='yellow')
textbox=Text(fg='green', bg='yellow')
textbox.pack()
window.mainloop()